config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'  
  get 'static_pages/home'
  
  resources :fighters, except: [:destroy, :edit, :update] do
    resources :skills, only: [:new, :create]
    
    collection do
      get :ranking
    end
  end
  
  resources :fights, only: [:new, :create, :show]
end

app/models/concerns/fight_symulator.rb
module FightSymulator
  extend ActiveSupport::Concern

  def check_winner
    winner_id = 0
    first_fighter_add_point = 0
    second_fighter_add_point = 0
    
    if (!self.first_fighter_id.nil? && !self.second_fighter_id.nil? )
      first_fighter_points = 0;
      second_fighter_points = 0;
        
      first_fighter_add_point = self.first_fighter.experience_points
      second_fighter_add_point = self.second_fighter.experience_points
      
      self.first_fighter.skills.each do |i|
         first_fighter_points +=i.level * rand(1..5)
      end
    
       self.second_fighter.skills.each do |i|
        second_fighter_points +=i.level * rand(1..5)
      end
        
      if self.first_fighter.experience_points > self.second_fighter.experience_points
        first_fighter_points +=4
      elsif self.second_fighter.experience_points > self.second_fighter.experience_points
        second_fighter_points +=4
      end
      
      if first_fighter_points > second_fighter_points
        winner_id = self.first_fighter_id
        first_fighter_add_point += 10 
        second_fighter_add_point += 1
      
      elsif first_fighter_points < second_fighter_points
        winner_id = self.second_fighter_id
        first_fighter_add_point += 1
        second_fighter_add_point += 10
      
      else    
        random = rand(1..2)
        
        if random == 1
          winner_id = self.first_fighter_id
          first_fighter_add_point += 10
          second_fighter_add_point += 1
          
        elsif random == 2
          winner_id = self.second_fighter_id
          first_fighter_add_point += 1
          second_fighter_add_point += 10
        end
      end
    end
    
    self.winner_id = winner_id
    @fighters_points = [first_fighter_add_point, second_fighter_add_point]
    
  end    
end

app/models/fight.rb
class Fight < ActiveRecord::Base
  include FightSymulator
  
  belongs_to :first_fighter, class_name: "Fighter"
  belongs_to :second_fighter, class_name: "Fighter"
  belongs_to :winner, class_name: "Fighter"
  
  validates :first_fighter_id, presence: true
  validates :second_fighter_id, presence: true
  validates :winner_id, presence: true
  
  validate :check_first_fighter_id_and_second_fighter_id

  def check_first_fighter_id_and_second_fighter_id  
    if self.first_fighter_id == self.second_fighter_id
      errors.add(:first_fighter_id, "can't equal second fighter")
    end
  end
end

app/models/fighter.rb
class Fighter < ActiveRecord::Base
  before_validation :default_values, on: :create

  has_many :skills, dependent: :destroy
  has_many :fights, :class_name => "Fight", :foreign_key => "first_fighter_id", dependent: :destroy
  has_many :inverse_fights, :class_name => "Fight", :foreign_key => "second_fighter_id", dependent: :destroy
  has_many :won_fights, :class_name => "Fight", :foreign_key => "winner_id", dependent: :destroy
  
  validates :first_name, presence: true, length: {minimum: 1, maximum: 50}
  validates :last_name, presence: true, length: {minimum: 1, maximum: 50}
  validates :description, presence: true, length: {minimum: 15, maximum: 1000}
  validates_uniqueness_of :first_name, :scope => :last_name, :message => "in combination with last name already exists"
  
  has_attached_file :avatar
  validates :avatar, presence: true
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/ 
  validates_attachment_size :avatar, less_than: 512.kilobytes
  
  def default_values
    self.experience_points = 0     
  end
  
  def all_fights
    fights | inverse_fights
  end
  
  def self.find_active
    joins(:skills).group('fighter_id').having('count(fighter_id) >=2 ')
  end
  
  def self.find_fighter(first_name, last_name) 
    if first_name.empty?
      where("last_name like ?", "%#{last_name}%")
      
    elsif last_name.empty?
      where("first_name like ?", "%#{first_name}%")
      
    else
      where("first_name like ? OR last_name like ?", "%#{first_name}%", "%#{last_name}%")
    end
  end
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  belongs_to :fighter
  
  validates :fighter_id, presence: true
  validates :name, presence: true, length: {minimum: 2, maximum: 35}
  validates :level, presence: true
  validates_inclusion_of :level, :in => 0..5
  validates_uniqueness_of :fighter_id, :scope => :name, :message => "already has this skill"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/fighters_controller.rb
class FightersController < ApplicationController
  
  def index
    if params[:first_params] || params[:second_params]
      @fighters= Fighter.find_fighter(params[:first_params], params[:second_params]).paginate(page: params[:page], per_page: 5)
    else
      @fighters = Fighter.all.paginate(page: params[:page], per_page: 5)
    end
  end

  def show
    @fighter = Fighter.find(params[:id])
  end
  
  def ranking
    @per_page = 5
    @rank = 1
    @fighters = Fighter.order(experience_points: :desc, created_at: :asc).paginate(page: params[:page], per_page: @per_page)
  end

  def new
    @fighter = Fighter.new
  end
  
  def create
    @fighter = Fighter.new(fighter_params)

    if @fighter.save
      flash[:success] = "Fighter was successfully created!"
      redirect_to @fighter
    else
      render 'new'      
    end
  end
  
  private
  
    def fighter_params
      params.require(:fighter).permit(:first_name, :last_name, :description, :avatar)
    end
end

app/controllers/fights_controller.rb
class FightsController < ApplicationController
  
  def show
    @fight = Fight.find(params[:id])
    @winner = Fighter.find(@fight.winner_id)
  end
  
  def new
    @fight = Fight.new
    @fighters = Fighter.find_active
  end
  
  def create
    @fight = Fight.new(fight_params)
     
    @fighters_points = @fight.check_winner
     
    if @fight.save      
      @fight.first_fighter.update(experience_points: @fighters_points.first)
      @fight.second_fighter.update(experience_points: @fighters_points.second)
      
      flash[:success] = "Fight was successfully created!"
      redirect_to @fight
    else
      @fighters = Fighter.find_active
      render 'new'
    end
  end
  
  private
  
    def fight_params
      params.require(:fight).permit(:first_fighter_id, :second_fighter_id)
    end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :check_skills, only: [:new, :create] 
  
  def new 
    @skill = @fighter.skills.build
  end
  
  def create
    @skill = @fighter.skills.build(skill_params)

    if @skill.save
      flash[:success] = "Skill was successfully added!"
      redirect_to @fighter
    else
      render 'new'      
    end
  end
  
  private
  
    def skill_params
      params.require(:skill).permit(:name, :level)
    end
    
    def check_skills
      @fighter = Fighter.find(params[:fighter_id])
      
      redirect_to @fighter if @fighter.skills.count == 9
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fighters_helper.rb
module FightersHelper
end

app/helpers/fights_helper.rb
module FightsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/fighters/_form.html.erb
<div class="row">
  <%= form_for(@fighter, html: { multipart: true }) do |f| %>
  
    <%= render 'shared/error_communicat', object: f.object %>

    <div class="form-inputs">  
      <div class="field">
        <%= f.label :first_name %><br>
        <%= f.text_field :first_name, class: "form-control input-sm" %>
      </div>
      
      <div class="field">
        <%= f.label :last_name %><br>
        <%= f.text_field :last_name, class: "form-control input-sm" %>
      </div>
      
      <div class="field">
        <%= f.label :description %><br>
        <%= f.text_area :description, class: "form-control input-sm" %>
      </div>
      
      <div>
        <%= f.label :avatar %><br>
        <%= f.file_field :avatar %>
      </div>  
    </div>  
        
    <div class="form-action">
      <%= f.submit class: "btn btn-success" %>
    </div>
  
  <% end %>
</div>

app/views/fighters/index.html.erb
<h1>All fighters</h1>

<div class="search">
  <%= form_tag(fighters_path, method: "get", id: "search-form") do %>
  
    <div class="form-group col-xs-6">
      <%= text_field_tag :first_params, params[:first_params], class: "form-control input-sm", placeholder: "First name..." %>
    </div>
    
    <div class="form-group col-xs-6">
      <%= text_field_tag :second_params, params[:second_params], class: "form-control input-sm", placeholder: "Last name..." %>
    </div>
    
    <div class="form-action">
      <%= submit_tag "Search", class: "btn btn-primary btn-sm" %>
    </div>  
      
  <% end %>  
</div>

<%= render 'shared/pagination', object: @fighters %>

<% if @fighters.present? %>

  <ul class="fighters">
    <% @fighters.each do |fighter| %>
    
      <li>
        <%= render 'shared/avatar', locals: {fighter: fighter, size: "75x75", class: "img-rounded"} %>
        <%= link_to "#{fighter.first_name} #{fighter.last_name}", fighter %>
      </li>
      
    <% end %>
  </ul>

<% else %>    
   <div>No fighters found.</div>
<% end %>

<%= render 'shared/pagination', object: @fighters %>

app/views/fighters/new.html.erb
<div class="fighter-form">

  <h1>New fighter</h1>
  <%= render 'form' %>

</div>  

app/views/fighters/ranking.html.erb
<h1>Ranking fighters</h1>

<%= render 'shared/pagination', object: @fighters %>

<ul class="fighters">
  <% @fighters.each_with_index do |fighter, index| %>
  
    <li>     
      <% if params[:page] %>
        <% @rank += (params[:page].to_i-1) * @per_page %>
      <% end %>  
      
      <span class="place"><%= "#{index + @rank}." %></span>
      <%= render 'shared/avatar', locals: {fighter: fighter, size: "75x75", class: "img-rounded"} %>
      <%= link_to "#{fighter.first_name} #{fighter.last_name}", fighter %>
      <b> - <%= "#{fighter.experience_points} point(s)" %></b>
    </li>
    
  <% end %>
</ul>

<%= render 'shared/pagination', object: @fighters %>

app/views/fighters/show.html.erb
<div class="profile">
  
  <div class="avatar">
    <%= render 'shared/avatar', locals: {fighter: @fighter, size: "150x150", class: "img-circle"} %>
  </div>
  
  <div class="profile-information">
    <span class="big"><%= @fighter.first_name %> <%= @fighter.last_name %></span></br>
    <%= @fighter.description %></br>
    <%= @fighter.experience_points %> point(s)</br>
    <%= @fighter.all_fights.count %> fight(s)</br>
    <%= @fighter.won_fights.count %> won fight(s)</br>
    
    <% if @fighter.skills.count < 2 %>
      <%= link_to "Add skill to active a fighter",  new_fighter_skill_path(@fighter) %> 
    <% elsif @fighter.skills.count < 9 %>
      <%= link_to "Add skill", new_fighter_skill_path(@fighter) %>
    <% end %>
  </div>
  
  <div class="skills">
    <span class="big">Skills</span>
     <table class="table">
      
      <thead>     
        <tr>
          <th>No.</th>
          <th>Name</th>
          <th>Level</th>
        </tr>
      </thead>
    
      <tbody>     
        <% @fighter.skills.each_with_index do |skill, index| %>
          <tr>
            <th><%= index + 1 %></th>
            <td class="text-left"><%= skill.name %></td>
            <td class="text-left"><%= skill.level %></td>
          </tr> 
        <% end %>
      </tbody>
      
    </table>  
  </div>
  
  <div class="fights">
    <span class="big">Fights</span> 
    <table class="table">
      
      <thead>  
        <tr>
          <th>No.</th>
          <th>First Fighter</th>
          <th>Second Fighter</th>
          <th>Winner</th>
        </tr>
      </thead>
    
      <tbody>     
        <% @fighter.all_fights.each_with_index do |fight, index| %> 
          <tr>
            <th><%= index + 1 %></th>
            <td class="text-left"><%= "#{fight.first_fighter.first_name} #{fight.first_fighter.last_name}" %></td>
            <td class="text-left"><%= "#{fight.second_fighter.first_name} #{fight.second_fighter.last_name}" %></td>
            <td class="text-left"><%= "#{fight.winner.first_name} #{fight.winner.last_name}" %></td>
          </tr>  
        <% end %>
      </tbody>
      
    </table>  
  </div> 
</div>

app/views/fights/new.html.erb
<div class="fighter-form">

  <h1>New Fight</h1>
  
  <div class="row">
    <%= form_for(@fight) do |f| %>
  
      <%= render 'shared/error_communicat', object: f.object %>

      <div class="form-inputs">  
        <div class="field">
          <%= f.label :first_fighter %><br>
          <%= f.select :first_fighter_id, @fighters.collect{ |u| ["#{u.first_name} #{u.last_name}", u.id] }, include_blank: true %>
        </div>
      
        <div class="field">
          <%= f.label :second_fighter %><br>
          <%= f.select :second_fighter_id, @fighters.collect{ |u| ["#{u.first_name} #{u.last_name}", u.id] }, include_blank: true %>
        </div>      
      </div>  
        
      <div class="form-action">
        <%= f.submit "Fight", class: "btn btn-danger" %>
      </div>
    
    <% end %>
  </div>
</div>  

app/views/fights/show.html.erb
<div class="home"> 
  <ul class="list-inline">
    
    <li>  
      <%= render 'shared/avatar', locals: {fighter: @fight.first_fighter, size: "100x100", class: "img-circle"} %>
      
      <div class="profile-information">
        <%= link_to fighter_path(@fight.first_fighter) do %>
          <b><%= @fight.first_fighter.first_name %> <%= @fight.first_fighter.last_name %></b>
        <% end %>
      </div>
    </li>
  
    <li>
      <div class="fight">VS</div>
    </li>
  
    <li>
      <%= render 'shared/avatar', locals: {fighter: @fight.second_fighter, size: "100x100", class: "img-circle"} %>
      
      <div class="profile-information">
        <%= link_to fighter_path(@fight.second_fighter) do %>
          <b><%= @fight.second_fighter.first_name %> <%= @fight.second_fighter.last_name %></b>
        <% end %>
      </div>
    </li>
  </ul>
  
  <div class="fight">Winner</div>
  
  <%= render 'shared/avatar', locals: {fighter: @winner, size: "100x100", class: "img-circle"} %>
  
  <div class="profile-information">
    <%= link_to fighter_path(@winner) do %>
        <b><%= @winner.first_name %> <%= @winner.last_name %></b>
    <% end %>
  </div>
</div>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-default">
    <div class="navbar-fluid">
      
      <div class="navbar-header">
        <%= link_to "FightClub", root_path, class: "navbar-brand"  %>
      </div>
      
      <div id="navbar" class="navbar-collapse collapse">   
        <ul class="nav navbar-nav">
          <li><%= link_to "Ranking",  ranking_fighters_path %></li>
          <li><%= link_to "Fighters", fighters_path %></li>
        </ul>
        
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "New Fighter", new_fighter_path %></li>
          <li><%= link_to "Fight", new_fight_path %></li>
        </ul>
      </div>
      
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FightClub</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>
  
  <div class="content">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
  </div>

</body>
</html>

app/views/shared/_avatar.html.erb
<%= image_tag locals[:fighter].avatar.url(), size: locals[:size], class: locals[:class],
              title: "#{locals[:fighter].first_name} #{locals[:fighter].last_name}"  %>

app/views/shared/_error_communicat.erb
<% if object.errors.any? %>
  <div class="error_explanation">
    <div class="alert alert-danger">    
      <ul>
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/shared/_error_communicat.html.erb
<% if object.errors.any? %>
  <div class="error_explanation">
    <div class="alert alert-danger">    
      <ul>
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/shared/_pagination.html.erb
<%= will_paginate object, previous_label: "Previous", next_label: "Next", inner_window: 3,
                          outer_window:1, renderer: BootstrapPagination::Rails %>

app/views/skills/new.html.erb
<div class="skill-form">

  <h2>Add skill to <%= "#{@fighter.first_name} #{@fighter.last_name}" %></h2>
  <p class="skill">Each fighter should have from 2 to 9 skills to could fight</p>
  
  <div class="row">
    <%= form_for([@fighter, @skill]) do |f| %>
  
      <%= render 'shared/error_communicat', object: f.object %>

      <div class="form-inputs">  
        <div class="field">
          <%= f.label :name %><br>
          <%= f.text_field :name, class: "form-control input-sm" %>
        </div>
      
        <div class="field">
          <%= f.label :level %><b>(0-5)</b><br>
          <%= f.text_field :level, class: "form-control input-sm" %>
        </div>     
      </div>  
        
      <div class="form-action">
        <%= f.submit "Add Skill", class: "btn btn-success" %>
      </div>
  
    <% end %>
  </div>  
</div>  

app/views/static_pages/home.html.erb
<div class="center">
  <div class="home">
    
    <p class="title">Welcome to Fight Club!</p>
    <%= link_to new_fighter_path do %>
     <button class="btn btn-lg btn-success">New Fighter!</button>
    <% end %>
    
   </div>
</div>
  
   